version: '3.8'

services:
  drupal:
    image: drupal:latest
    container_name: drupal
    ports:
      - "81:80"
    depends_on:
      - db
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
      - DRUPAL_DB_NAME=drupal
    volumes:
      - drupal_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: drupal_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  drupal_data:
  mysql_data:
