version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "82:80"
    networks:
      - redDocker
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpressuser
      - WORDPRESS_DB_PASSWORD=wordpresspassword
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    networks:
      - redDocker
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpressuser
      - MYSQL_PASSWORD=wordpresspassword
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  redDocker:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
